---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/createContactList.html"
          highlight: "0-44"
        - file: "javascript/createContactList.html"
          highlight: "9-11"
        - file: "javascript/createContactList.html"
          highlight: "12-27"
        - file: "javascript/createContactList.html"
          highlight: "29-38"
