---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/createContactList.html"
          highlight: "0-40"
        - file: "javascript/createContactList.html"
          highlight: "9-11"
        - file: "javascript/createContactList.html"
          highlight: "12-25"
        - file: "javascript/createContactList.html"
          highlight: "27-36"
