---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/createCampaign.html"
          highlight: "0-77"
        - file: "javascript/createCampaign.html"
          highlight: "9-11"
        - file: "javascript/createCampaign.html"
          highlight: "12-38"
        - file: "javascript/createCampaign.html"
          highlight: "40-61"
        - file: "javascript/createCampaign.html"
          highlight: "63-71"
