---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/presence_subscription.html"
          highlight: "0-100"
        - file: "javascript/presence_subscription.html"
          highlight: "17-27"
        - file: "javascript/presence_subscription.html"
          highlight: "29-36"
        - file: "javascript/presence_subscription.html"
          highlight: "37-43"
        - file: "javascript/presence_subscription.html"
          highlight: "51-60"
