---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/presence_subscription.html"
          highlight: "0-133"
        - file: "javascript/presence_subscription.html"
          highlight: "42-61"
        - file: "javascript/presence_subscription.html"
          highlight: "63-71"
        - file: "javascript/presence_subscription.html"
          highlight: "73-99"
        - file: "javascript/presence_subscription.html"
          highlight: "108-118"
