---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/example.html"
          highlight: "0-100"
        - file: "javascript/example.html"
          highlight: "29-35"
        - file: "javascript/example.html"
          highlight: "6-15"
        - file: "javascript/example.html"
          highlight: "17-24"
csharp:
    displayName: C#
    steps:
        - file: "csharp/MainForm.cs"
          highlight: "0-100"
        - file: "csharp/MainForm.cs"
          highlight: "20-28"
        - file: "csharp/MainForm.cs"
          highlight: "55-66"
        - file: "csharp/MainForm.cs"
          highlight: "36-52"
ruby:
    displayName: Ruby
    steps:
        - file: "ruby/script.rb"
          highlight: "0-100"
        - file: "ruby/script.rb"
          highlight: "28-41"
        - file: "ruby/script.rb"
          highlight: "16-27"
        - file: "ruby/script.rb"
          highlight: "8-14"
