---
ruby:
    displayName: Ruby
    steps:
        - file: "ruby/server.rb"
          highlight: "0-100"
        - file: "ruby/server.rb"
          highlight: "1-13"
        - file: "ruby/server.rb"
          highlight: "24-45"
        - file: "ruby/server.rb"
          highlight: "53-70"
        - file: "ruby/my_info.html"
          highlight: "8-16"
        - file: "ruby/server.rb"
          highlight: "72-77"
nodejs:
    displayName: NodeJS
    steps:
        - file: "nodejs/server.js"
          highlight: "0-150"
        - file: "nodejs/server.js"
          highlight: "108-109"
        - file: "nodejs/server.js"
          highlight: "13-33"
        - file: "nodejs/server.js"
          highlight: "46-86"
        - file: "nodejs/my_info.html"
          highlight: "8-16"
        - file: "nodejs/server.js"
          highlight: "89-106"
csharp:
    displayName: ASP.NET
    steps:
        - file: "asp-dot-net/authorization_code_aspdotnet/Controllers/HomeController.cs"
          highlight: "0-95"
        - file: "asp-dot-net/authorization_code_aspdotnet/Controllers/HomeController.cs"
          highlight: "16-16"
        - file: "asp-dot-net/authorization_code_aspdotnet/Controllers/HomeController.cs"
          highlight: "44-49"
        - file: "asp-dot-net/authorization_code_aspdotnet/Controllers/HomeController.cs"
          highlight: "59-73"
        - file: "asp-dot-net/authorization_code_aspdotnet/Controllers/HomeController.cs"
          highlight: "75-81"
        - file: "asp-dot-net/authorization_code_aspdotnet/Controllers/HomeController.cs"
          highlight: "75-81"